### ISSUE TITLE
Retirar "Hadoop (Spark está tomando o espaço do Hadoop)" do README

### ISSUE THREAD

**Issue by Guilhermeslucas** [leportella/data-science-roadmap#19]
Estava lendo o repositório e notei essa frase. É chatisse da minha parte mas é que, sendo um pouco rigoroso, Spark e Hadoop são coisas diferentes. Spark pode estar substituindo o MapReduce, já que são frameworks com funções próximas. Porém, o projeto Hadoop tem muitas ferramentas, como o MapReduce já citado, o HDFS, Hive, Pig, Yarn, etc.

Desculpem se estou sendo chato demais ou falando algo que não faz sentido.
Muito obrigado pela atenção.

**Comment by leportella** [comment]
Oi @Guilhermeslucas tudo bem?
Estamos desenvolvendo esse repositório de forma totalmente colaborativa. 
Muitas pessoas que contribuiram são iniciantes ou não estão totalmente dentro da área. É interessante que você faça um PR pra corrigir esse tipo de informação que não está 100% correta. Também é bem-vindo para expandir com outros termos ou materiais!

Abs

**Comment by Guilhermeslucas** [comment]
Muito legal. Vou fechar essa issue e abrir um PR!

**Comment by leportella** [comment]
Ótimo! Obrigada por contribuir! :)

**Comment by Guilhermeslucas** [comment]
Eu que agradeço. Projeto sensacional.
