### ISSUE TITLE
Seção para textos interessantes

### ISSUE THREAD

**Issue by Guilhermeslucas** [leportella/data-science-roadmap#23]
O que acham de criar uma seção com links para textos interessantes sobre data science? Estava pensando em colocar algo nessa linha:
https://dl.acm.org/citation.cfm?doid=2831360.2831365

Vi que existe a seção awesome news, mas não sei se daria pra incluir textos como esse nela.
Muito obrigado.

**Comment by leportella** [comment]
Oi @Guilhermeslucas ! 
Na verdade eu criei a seção de "awesome news" pra colocar links em gerais, por exemplo matérias de produtos inovadores e etc. Menos conteúdo mesmo e mais notícias relevantes pra quem trabalha na área.
Acho que esse tipo de link que você mandou encaixa sim nesse contexto ou mesmo podemos criar um documento específico para conteúdo de Big Data (coisa que ainda não temos hoje!). Acho que o segundo approach tem mais futuro. O que acha?

**Comment by Guilhermeslucas** [comment]
Acho uma excelente ideia. Mando um pull request?

**Comment by leportella** [comment]
Por favor :) e coloque ele fechando esta issue
